window.onload = function(){

const pl=[".O mnie", "Litwo! Ojczyzno moja! ty jesteś jak zdrowie: Ile cię trzeba cenić, ten tylko się dowie, kto cię stracił. Dziś piękność twą w całej ozdobie Widzę i opisuję, bo tęsknię po tobie.", ".CO ROBIĘ?", "Kreatwność", "Litwo! Ojczyzno moja! ty jesteś jak zdrowie: Ile cię trzeba cenić, ten tylko się dowie, kto cię stracił. Dziś piękność twą w całej ozdobie Widzę i opisuję, bo tęsknię po tobie.", "Kodowanie", "Litwo! Ojczyzno moja! ty jesteś jak zdrowie: Ile cię trzeba cenić, ten tylko się dowie, kto cię stracił. Dziś piękność twą w całej ozdobie Widzę i opisuję, bo tęsknię po tobie.", "WWW", "Litwo! Ojczyzno moja! ty jesteś jak zdrowie: Ile cię trzeba cenić, ten tylko się dowie, kto cię stracił. Dziś piękność twą w całej ozdobie Widzę i opisuję, bo tęsknię po tobie.", ".AKTWNE PROJEKTY", "Projekt 1", "Litwo! Ojczyzno moja! ty jesteś jak zdrowie: Ile cię trzeba cenić, ten tylko się dowie, kto cię stracił. Dziś piękność twą w całej ozdobie Widzę i opisuję, bo tęsknię po tobie.", "Projekt 2", "Litwo! Ojczyzno moja! ty jesteś jak zdrowie: Ile cię trzeba cenić, ten tylko się dowie, kto cię stracił. Dziś piękność twą w całej ozdobie Widzę i opisuję, bo tęsknię po tobie.", "Projekt 3", "Litwo! Ojczyzno moja! ty jesteś jak zdrowie: Ile cię trzeba cenić, ten tylko się dowie, kto cię stracił. Dziś piękność twą w całej ozdobie Widzę i opisuję, bo tęsknię po tobie.", "Wszystkie prawa zastrzeżone"];
const en=[".About me", "Welcome, gentlemen! ladies that have their toes, Unplagued with corns will have a bout with you. Ah ha, my mistresses! which of you all. Will now deny to dance? she that makes dainty.", "WHAT I'M DOING", "Creativity", "Welcome, gentlemen! ladies that have their toes, Unplagued with corns will have a bout with you. Ah ha, my mistresses! which of you all. Will now deny to dance? she that makes dainty.", "Coding", "Welcome, gentlemen! ladies that have their toes, Unplagued with corns will have a bout with you. Ah ha, my mistresses! which of you all. Will now deny to dance? she that makes dainty.", "WWW", "Welcome, gentlemen! ladies that have their toes, Unplagued with corns will have a bout with you. Ah ha, my mistresses! which of you all. Will now deny to dance? she that makes dainty.", ".ACTIVE PROJECTS", "Project 1", "Welcome, gentlemen! ladies that have their toes, Unplagued with corns will have a bout with you. Ah ha, my mistresses! which of you all. Will now deny to dance? she that makes dainty.", "Project 2", "Welcome, gentlemen! ladies that have their toes, Unplagued with corns will have a bout with you. Ah ha, my mistresses! which of you all. Will now deny to dance? she that makes dainty.", "Project 3", "Welcome, gentlemen! ladies that have their toes, Unplagued with corns will have a bout with you. Ah ha, my mistresses! which of you all. Will now deny to dance? she that makes dainty.", "All rights reserved"];
const about_me_tittle=document.getElementById("about-me-title");


    const button_en = document.getElementById("buttonen");
    button_en.onClick = function () {
        about_me_tittle.innerHTML=en[0];
        console.log("przycisk klikniety");

    };
};